[install]
exact = true

[workspaces]
packages = ["apps/*", "packages/*", "database"]

[workspaces.catalogs.runtime]
"bun-types" = "1.3.0"
"@types/node" = "24.7.2"

[workspaces.catalogs.api]
"@elysiajs/eden" = "1.4.4"
"elysia" = "1.4.12"

[workspaces.catalogs.client]
"react" = "19.2.0"
"react-dom" = "19.2.0"
"babel-plugin-react-compiler" = "1.0.0"
"@types/react" = "19.2.0"
"@types/react-dom" = "19.2.0"