import type { Metadata } from "next"
import type { ReactNode } from "react"

import { UiToolkitProvider } from "@1st/ui-toolkit"

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <UiToolkitProvider>{children}</UiToolkitProvider>
      </body>
    </html>
  )
}
