import type { Metadata } from "next"
import type { ReactNode } from "react"

import { Provider } from "@1st/react-toolkit/components"

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider.ThemeProvider>
          {children}
        </Provider.ThemeProvider>
      </body>
    </html>
  )
}
